package gui.panels;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.LayoutManager;
/**
 *
 * @author Aminovski
 */
public class ImagePanel extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;


	/**
     * Creates new form ImagePanel
     */
    public ImagePanel() {
        
    }
    public ImagePanel(LayoutManager lm){
        super(lm);
    }
    public Image getImage() {
        return BackGroundimage;
    }
    public void setImage(Image image) {
        this.BackGroundimage = image;
        Dimension size=new Dimension(image.getWidth(this),image.getHeight(this));
        this.setPreferredSize(size);
        this.setMinimumSize(size);
        this.setMaximumSize(size);
        this.setSize(size);
        this.setOpaque(false);
    }
 
    public static void main(String[] args) {
       
    }
    @Override
    public void paintComponent(Graphics g){
    if(this.BackGroundimage!=null){
        g.drawImage(BackGroundimage, 0, 0,800,600,null);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private Image BackGroundimage;
}

