package gui.panels;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JPanel;

/**
 *
 * @author Aminovski
 */
public class TransparentPanel extends javax.swing.JPanel {

    /**
     * Creates new form TransparentPanel
     */
    public TransparentPanel(){
       
        this.setSize(50,50);
        this.setOpaque(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public static void main(String[] args) {
       
    }
   
}
